name: Weekly Retrain
on:
  schedule:
    - cron: '0 0 * * 0'   # every Sunday 00:00 UTC
  workflow_dispatch:       # allow manual run from GitHub UI

jobs:
  retrain:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: |
          python -m pip install --upgrade pip
          python -m pip install "torch==2.4.1" "numpy==1.26.4" "pandas==2.3.2" "scikit-learn==1.5.1" "ccxt" "joblib"
          python train_models.py
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add lstm.pth scaler.pkl gb.pkl
          git commit -m "chore(models): weekly retrain artifacts" || echo "No changes"
          git push
